### ISSUE TITLE
Auto Download when new story is added

### ISSUE THREAD

**Issue by ghost** [notcammy/PyInstaStories#10]
Could auto download be implemented?

**Comment by dvingerh** [comment]
I won't implement any functionality to allow polling for new stories, but you can use a simple batch/bash loop script to achieve the same thing.

###### Windows


```batch
:loop
python3 pyinstastories.py -d jacobsartorius justinbieber lilhankwilliams
timeout 60 > nul
goto loop
```

###### Linux / MacOS

```shell
while true
do
    python3 pyinstastories.py -d jacobsartorius justinbieber lilhankwilliams
    sleep 60
done
```
