### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by Etherrrr** [notcammy/PyInstaStories#15]
It seems i cannot login since the log shows:
```
[E] Client Error: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/2619762557/bdVtvQsuLC/", "api_path": "/challenge/2619762557/bdVtvQsuLC/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail", "error_type": "checkpoint_challenge_required"}
```
Is there any way to avoid this?

**Comment by dvingerh** [comment]
Related info: https://github.com/ping/instagram_private_api/issues/44#issuecomment-354938425 and https://github.com/ping/instagram_private_api/issues/91#issuecomment-406982208.

> Is there any way to avoid this?

Your best bet is to create a new account on the same device / IP Address / location the application is used at. Other than that, no
