### ISSUE TITLE
ModuleNotFoundError: No module named 'instagram_private_api'

### ISSUE THREAD

**Issue by mortim** [notcammy/PyInstaStories#16]
-  OS: Ubuntu 18.04.2 LTS x86_64
-   Kernel: 4.18.0-20-generic
-   Shell: fish

Hello, I have a problem, the program returns an error according to which it does not find the module "instagram_private_api" yet I installed it with:
```pip install git+https://git@github.com/ping/instagram_private_api.git@1.6.0```

Any ideas?

**Comment by dvingerh** [comment]
Make sure pip installs the package for the correct python version. For instance if pip installs the package for python 2 you cant use it with python 3. If you have pip3 try installing it with that also.

**Comment by mortim59** [comment]
```

**Comment by mortim** [comment]
When I try to install with pip3 I have this: 
```
Collecting git+https://git@github.com/ping/instagram_private_api.git@1.6.0
  Cloning https://git@github.com/ping/instagram_private_api.git (to 1.6.0) to /tmp/pip-q1bqqty5-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-q1bqqty5-build/
```

**Comment by dvingerh** [comment]
Install [setuptools](https://packaging.python.org/tutorials/installing-packages/#ensure-pip-setuptools-and-wheel-are-up-to-date)

**Comment by mortim** [comment]
> Install [setuptools](https://packaging.python.org/tutorials/installing-packages/#ensure-pip-setuptools-and-wheel-are-up-to-date)

The link not working.

**Comment by dvingerh** [comment]
https://packaging.python.org/tutorials/installing-packages/#ensure-pip-setuptools-and-wheel-are-up-to-date

`python -m pip install --upgrade pip setuptools wheel`
`python3 -m pip install --upgrade pip setuptools wheel`

If it doesnt work then theres not much else i can suggest since it's not a problem related to my project.

**Comment by mortim** [comment]
It works thanks ! But I have another question. How to add logins if my account is connected with Facebook ?

**Comment by dvingerh** [comment]
I'm unsure if it's possible with the library thats being used currently. There's an open issue regarding it on its repo as well. you can try https://github.com/ping/instagram_private_api/issues/169#issuecomment-494619085 but otherwise you'll have to unlink facebook or create a new account.

**Comment by mortim** [comment]
Okay thanks
