### ISSUE TITLE
[BUG] List index out of range

### ISSUE THREAD

**Issue by ghost** [notcammy/PyInstaStories#18]
Hi,
i currently have a batch running every couple of hours to download stories for list of users, and I just noticed that there's a new argument to download hq videos, so I added the argument to the command in the batch file and started having errors.
When the script reaches the 16 user out of 50 users from list of users i get this error: 

[I] Downloading high quality videos enabled. Ffmpeg will be used.
----------------------------------------------------------------------
[E] An error occurred: list index out of range

Here's the command that is used from the batch:
python pyinstastories.py --hq-videos --batch-file usernames.txt --username john --password 1234

**Comment by dvingerh** [comment]
I've encountered this issue before as well but I don't have a way to reproduce it. Will probably take a while  to resolve. I suggest not using the argument for now as the quality difference is negligible

**Comment by ghost** [comment]
I can guide you on how to reproduce it, and send you the users list.
I will even create a new Instagram account for you to test.
Will you give it a shot?

**Comment by dvingerh** [comment]
The issue should be resolved now, but thanks for the offer.
