### ISSUE TITLE
[Enhancement] Display appropriate message 

### ISSUE THREAD

**Issue by ghost** [notcammy/PyInstaStories#21]
Hi,
So when trying to download stories from a private user that I don't follow, I get the following message "There are no recent stories to process for this user." 
Could Display a more appropriate message so its easier to detect errors and to know if a certain user removed you from their followers list?

**Comment by ghost** [comment]
Oh and thanks for working on this great script !

**Comment by notcammy** [comment]
print('-' * 70)

**Comment by dvingerh** [comment]
This should now be added and working in v2.3.

**Comment by ghost** [comment]
Cheers!

**Comment by ghost** [comment]
@notcammy Any idea on how to check if a certain private user have hidden stories from you?
The way I manually check:
If a certain user have hidden stories from you, you won't be able to see his highlights and his stories.
( Thanks for bearing with me, I'm thinking about studying about python to help out with this project)

**Comment by dvingerh** [comment]
@rabe398 I don't know but I doubt the API returns such info.
