### ISSUE TITLE
the profile is in my friend's list. but i got this message: [I] There are no recent stories to process for this user.

### ISSUE THREAD

**Issue by carlhung** [notcammy/PyInstaStories#24]
I can't download any images of profiles in my friend's list.

$ python3 pyinstastories.py --username xxxx --password xxxx --download xxxx
[I] PYINSTASTORIES (SCRIPT V2.5 - PYTHON V3.7.3) - 11:32:15 PM
[I] Using cached login cookie for "xxxx".
[I] Login to "xxxx" OK!
[I] Login cookie expiry date: 2019-11-27 at 11:20:53 PM
[I] Files will be downloaded to /media/xxxxxxxxxxxx
[I] Getting stories for: xxxxxx
[I] There are no recent stories to process for this user.

**Comment by dvingerh** [comment]
The user may have chosen to hide stories from you, even though you are following him or her.
Please check if the problem also occurs with your own private accounts.
Either way I've tested downloading a private account I am following and can't reproduce the issue.

**Comment by carlhung** [comment]
I don’t really think so. As I tried about 5-6 users. None of them worked.

**Comment by dvingerh** [comment]
Can you delete your `json_feed.json` file (if one exists), run the attached  script below and then post the new json file here?

The usual response when there are no stories would be when `reel` is null:
```json
{"broadcast": null, "reel": null, "status": "ok"}
```
but perhaps the response is different this time and it might give a clue as to what's going on. 

[pyinstastories.zip](https://github.com/notcammy/PyInstaStories/files/3559902/pyinstastories.zip)
