### ISSUE TITLE
Joining 15+ second stories automatically.

### ISSUE THREAD

**Issue by remlap** [notcammy/PyInstaStories#25]
Right now I am using ffmpeg to combine stories that are 15+ seconds long automatically with:

`for f in $(ls -hatr *.mp4); do echo file $f >> mylist.txt; done; ffmpeg -f concat -i mylist.txt -c copy stitched-video.mp4; rm mylist.txt`

I then open up stitched-video.mp4 in audacity and then use the trunucate silence filter so I get clean audio.

I then save as a m4a and remux the audo with stitched-video.mp4.

I was wondering if you had any ideas on how to do this automatically, I have tried ffmpeg silenceremove filter and it just isn't up to the task of remove 0.01 of silence.

Thanks!

**Comment by dvingerh** [comment]
I wouldn't know, this isn't related to my script and I'm not experienced with ffmpeg nor audacity. 
There seems to be a Scripting plugin for Audacity but you'll have to build from source before you can use it. https://manual.audacityteam.org/man/scripting.html
