### ISSUE TITLE
"InvalidURL URL can't contain control characters."

### ISSUE THREAD

**Issue by Baemir** [notcammy/PyInstaStories#27]
So my setup with this script was working fine until recently the drive where I was saving the Stories failed and I had to move the folders over to a different one (along with the script itself and the login cookies, of course). Now I'm seeing this error over and over for any username I input:

```
----------------------------------------------------------------------
 [E] (1) Download failed: InvalidURL URL can't contain control characters. '/api/v1/users/************\r/usernameinfo/' (found at least '\r').
 [W] Trying again in 5 seconds.
----------------------------------------------------------------------
[E] (2) Download failed: InvalidURL URL can't contain control characters. '/api/v1/users/************\r/usernameinfo/' (found at least '\r').
[W] Trying again in 5 seconds.
----------------------------------------------------------------------
[E] (3) Download failed: InvalidURL URL can't contain control characters. '/api/v1/users/************\r/usernameinfo/' (found at least '\r').

[W] Trying again in 5 seconds.
----------------------------------------------------------------------
[E] Retry failed three times, skipping user.
```

I redownloaded the script and checked my text file with the list of usernames in case either file was corrupted after the drive failed, but the problem persists. So is this a problem on my end, or was the drive failure just a coincidence and it's actually that IG changed something on their end?

**Comment by dvingerh** [comment]
I tested with Python 3.7.5 and on multiple machines (windows and debian), I can download stories just fine. I recommend reinstalling Python as well as the dependencies this script uses and see how that goes but in any case I can't reproduce the issue.

**Comment by Baemir** [comment]
It's working again after setting python3.7 as the default using update--alternatives, installing python3-pip and then installing the API and running the script with said version. For some reason python2 doesn't seem to do the job anymore? I may have just broken it on my end, if it's working fine for other people. 
Thanks for your help.
