### ISSUE TITLE
Config file option to provide IG profiles

### ISSUE THREAD

**Issue by sabueso** [notcammy/PyInstaStories#3]
HI!

Would be great to load a file as "profiles.txt" with all the needed profiles to be downloaded right there. Actually, the workaround

```sh
$ python pyinstastories.py -d `cat profiles.txt`
```

should work, but maybe is not the more elegant solution.

What do you think?
Thanks!

**Comment by dvingerh** [comment]
This has now been added in https://github.com/notcammy/PyInstaStories/commit/b44c7a203d2b9fc74d561fd485db924a5262de42. 🙂 

Use `--batch-file` or simply `-b` to pass a text file with usernames.

**Comment by sabueso** [comment]
Great job! ;)
