### ISSUE TITLE
Challenge Required 

### ISSUE THREAD

**Issue by pi43r** [notcammy/PyInstaStories#30]
Hey,
I am getting stuck at the challenge. Somehow I am unable to pass it. 

```[E] Client Error: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/4231068/LeMzj9l17/", "api_path": "/challenge/4231068/LeMzj9l17/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail", "error_type": "checkpoint_challenge_required"}```

**Comment by dvingerh** [comment]
See https://github.com/notcammy/PyInstaStories/issues/19 and read through https://github.com/notcammy/PyInstaLive/issues/57
