### ISSUE TITLE
[Feature Request] Add highlights download

### ISSUE THREAD

**Issue by wangxu94** [notcammy/PyInstaStories#33]
Please add the ability to download Highlights (archived stories). Thanks!

**Comment by dvingerh** [comment]
I'll take a look at implementing it later this week.

**Comment by dvingerh** [comment]
Implementing this requires a large rewrite of code, the used API library does not support the endpoint responsible for retrieving highlight medias. It's unlikely that I'll do this anytime soon, so in the meantime use an alternative project like https://github.com/instaloader/instaloader to download highlights.
