### ISSUE TITLE
Not showing as a user who viewed story

### ISSUE THREAD

**Issue by jagilley** [notcammy/PyInstaStories#36]
I've found that when I use this library to view stories, I don't show up in the story poster's "people who viewed your story" section. Is this as it's designed to be, and is there a way to change this?

**Comment by dvingerh** [comment]
It's by design. It's not possible right now to mark them as seen but the endpoint responsible for it [seems to be supported by the API dependency](https://instagram-private-api.readthedocs.io/en/latest/api.html?highlight=story%20seen#instagram_private_api.Client.media_seen) so it could be added

**Comment by jagilley** [comment]
Thanks! Maybe I'll add the functionality and submit a PR with the added functionality, if you'd be open to it

**Comment by dvingerh** [comment]
No problem. but make it an optional functionality through the use of an extra argument (name at your discretion)
