### ISSUE TITLE
Can't download anything -  'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by InTheFlipside** [notcammy/PyInstaStories#43]
Hey, 
Sorry to bother you, I have an error while running the script. I provide the cookie in the credentials.json and it works but when i'm running the command : 
python instagram.py --download sci 
I have this error : 
```
----------------------------------------------------------------------
[I] PYINSTASTORIES (SCRIPT V2.6 - PYTHON V3.6.0) - 04:05:07 PM
----------------------------------------------------------------------
[E] Unexpected Exception: 'list' object has no attribute 'get'
----------------------------------------------------------------------
```
it's python3.6 on a windows 10

**Comment by dvingerh** [comment]
You don't have to manually provide cookies in the json file, that file is automatically generated when you login with the appropriate arguments. Le me know if you did everything correctly and are still experiencing issues since I can't reproduce the problem.

> The `--username` and `--password` arguments are required to generate a new cookie file or when an existing cookie file has expired. You can omit these two arguments if there is a working login cookie file available already.
