### ISSUE TITLE
Account gets flagged when uses Pyinstastories

### ISSUE THREAD

**Issue by rabea98** [notcammy/PyInstaStories#47]
No

**Comment by sensorius** [comment]
@rabea98 I've made similiar experiences starting last week, two accounts have been disabled. Did you get the account verification challenge while attempting to login manually or were you able to see an error code in "instagram_private_api " used by pyinstastories?

**Comment by rabea98** [comment]
No

**Comment by babyrig** [comment]
I have the same issue but with "24 hour review" still waiting to see what will happen, but when the account get disabled it's forever ?

**Comment by sensorius** [comment]
@babyrig I was not able to reactivate my flagged accounts.

**Comment by babyrig** [comment]
I found this may or may not help with disabled accounts.

[https://socialtipster.co/instagram-account-disabled/](url)
