### ISSUE TITLE
PyinstaStories stops when multiple users are provided and one is not working

### ISSUE THREAD

**Issue by sabueso** [notcammy/PyInstaStories#5]
Hi

When you provide several users (not in batch mode) and one of them is not working or maybe, changed the name of the account, the download is stopped in this profile with the message

```
[I] Getting stories for user: XXXXXXXXXXX
----------------------------------------------------------------------
[E] An error occurred: Not Found: User not found
```

Is this normal? This will happen in the batch mode too?

Thanks!

**Comment by dvingerh** [comment]
This should now be fixed with https://github.com/notcammy/PyInstaStories/commit/34366413b75ad6b43e9a70d54dfa08e4f1127616 , try the newest version of the script 🙂

**Comment by sabueso** [comment]
Perfect! Works as expected. Thanks!
