### ISSUE TITLE
Skip Video Thumbnail

### ISSUE THREAD

**Issue by RVLVT** [notcammy/PyInstaStories#6]
Hi! I noticed that this script also downloading the video thumbnail, is there anyway to skip downloading video thumbnail?

**Comment by dvingerh** [comment]
Update the script to the latest version and you'll be able to pass `--no-thumbs` to skip downloading video thumbnails.

**Comment by RVLVT** [comment]
Awesome! Works perfectly
ooh.. just wanna point out that the URLopener got deprecation warning on python 3.7, changed it to `urllib.urlretrieve(video[0], save_path)` or `urllib.urlretrieve(image[0], save_path)` works fine for me.

**Comment by dvingerh** [comment]
Now using `urllib.urlretrieve()` 🙂
