### ISSUE TITLE
Users keeps changing their username

### ISSUE THREAD

**Issue by ghost** [notcammy/PyInstaStories#7]
I have the script running 24/7 checking stories for this specific user and I noticed that he keeps changing her username. Once he does that, the script won't download his stories until I manually enter his new username in the .txt file. 
Is it possible to implement a feature that once the script runs on a .txt file , it automatically writes all the identifiers of every username from the .txt file into a new one and the script continues to run from the identifier instead of the username, so once they change their username the script would continue?

**Comment by dvingerh** [comment]
You can now pass user ids yourself (get them from [here](https://codeofaninja.com/tools/find-instagram-user-id)).

Just add them to the txt file.
