### ISSUE TITLE
New feature request

### ISSUE THREAD

**Issue by ghost** [notcammy/PyInstaStories#9]
Hey,
Are you thinking about adding a new feature to check for new posts and download them? there's this java application that downloads all posts and it's not possible to run it 24/7

**Comment by dvingerh** [comment]
There are plenty of other Python scripts to achieve this, my script is solely for Instagram stories.
I won't add this, sorry.

https://github.com/rarcega/instagram-scraper
https://github.com/althonos/InstaLooter
